### ISSUE TITLE
Add instruction for how to exit from 'abroot shell' command

### ISSUE THREAD

**Issue by mrvladus** [Vanilla-OS/ABRoot#10]
Maybe add it to the help page. Because if I want to to exit shell and save my progress for next reboot I need to type `exit` or `exit 0`, but if I press `Ctrl+C` it just exits with an error and all progress is lost.

**Comment by matbme** [comment]
You can also use `Ctrl+d` to exit. It's a generally known keybind when dealing with SSH connections and containers, but I agree it's nice to tell the user it exists.

**Comment by mirkobrombin** [comment]
What we can do is alerting the user if an exit code is given, then asking for confirmation to drop or apply the transaction.

**Comment by matbme** [comment]
While we're at it, maybe we could pipe `rsync`'s output elsewhere to avoid dumping thousands of lines into stdout. I was thinking of doing something like a progress bar (TQDM style but in Go) but I'm not sure how doable this is with rsync.

**Comment by mirkobrombin** [comment]
One thing that I wanted to do from the beginning but I always postponed is to allows you to see a summary of the ABRoot transaction before applying it, i.e. the list of divergences. Maybe keeping the history of those changes for maintenance.

**Comment by kbdharun** [comment]
> One thing that I wanted to do from the beginning but I always postponed is to allows you to see a summary of the ABRoot transaction before applying it, i.e. the list of divergences. Maybe keeping the history of those changes for maintenance.

I would suggest keeping a history of the changes while displaying a progress bar by default. Maybe add a verbose flag to the abroot at the start to display it. I think displaying all the changes in a very fast-moving text might affect accessibility. So, I think progress bar similar to pip might be best

**Comment by matbme** [comment]
`rsync` has `--info=progress2` which shows a total transfer progress, but it's a bit ~ugly~ bare bones IMO.

![image](https://user-images.githubusercontent.com/48367298/210359469-e6905c4d-b8f6-43ef-ac16-9e48e237cf06.png)

**Comment by mirkobrombin** [comment]
ABRoot shell is no more a thing in ABRoot v2, so closing.
