### ISSUE TITLE
Running `abroot pkg apply` from the previous root causes it to become the current root again

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/ABRoot#100]
If, for instance, B is the current root, and the user boots into A and runs `abroot pkg apply`, ABRoot should recognize it is in the previous root and do not switch the current and previous roots, which is not the case at this point;.

**Comment by mirkobrombin** [comment]
Maybe there is a bug in the workflow, the getPartitions method checks the mount point to identify the current 
https://github.com/Vanilla-OS/ABRoot/blob/764e9021cd887ad637dc1652a6a373f94beb37dd/core/root.go#L52

**Comment by mirkobrombin** [comment]
I did several tests and it seems that this bug is no longer present, potentially fixed in one of the last commits
