### ISSUE TITLE
Prevent `pkg apply` to apply changes if already applied

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/ABRoot#106]
This behavior could be confusing to the user which could still apply changes thinking that these have not been applied.

**Comment by minima1cha0s** [comment]
I can create a PR for this issue. 
Just for my understanding if GetAddPackagesString and GetAddPackagesString return empty string there is no need to apply right ?

**Comment by mirkobrombin** [comment]
You are in right. For the dependencies list, check the workflow please

**Comment by arejula27** [comment]
Does the issue still need attention?

**Comment by mirkobrombin** [comment]
> Does the issue still need attention?

Not sure, this could be already fixed must check the source
