### ISSUE TITLE
Support fetching update details via API

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/ABRoot#115]
Since we dropped the usage of the package manager (which is now eventually used during the build process only), we can't list changes from the packages repository. However this would be pointless as much of Vanilla OS is built using modules and not packages.

The idea is to allow ABRoot pulling details for an update using its digest.

**Comment by taukakao** [comment]
I just checked and I think this is done already. 
Abroot is checking the digest.

https://github.com/Vanilla-OS/ABRoot/blob/da1322733dc7200498e3eb271ee2359716c9ba73/core/registry.go#L60

**Comment by mirkobrombin** [comment]
> I just checked and I think this is done already. Abroot is checking the digest.
> 
> https://github.com/Vanilla-OS/ABRoot/blob/da1322733dc7200498e3eb271ee2359716c9ba73/core/registry.go#L60

Partially, we have the image digest but what this issue is about is taking details of the image, like what changed in the image. @matbme is working on a project named Differ which offers API that can be used to list those changes

**Comment by mirkobrombin** [comment]
introduced by [Differ](https://github.com/Vanilla-OS/Differ)
