### ISSUE TITLE
Follow-up: Use fs-local target for mounts in devices with no encryption enabled

### ISSUE THREAD

**Issue by mirkobrombin** [Vanilla-OS/ABRoot#117]
Ref: https://github.com/Vanilla-OS/ABRoot/pull/110#issuecomment-1689848670

**Comment by taukakao** [comment]
This is already implemented. https://github.com/Vanilla-OS/ABRoot/blob/8c0d48484ba8b758ea1f269a63ce1949dc5f22f8/core/system.go#L434C8-L434C8

Also the current changes are tracked in #159
