### ISSUE TITLE
Past/Present instead of Present/Future

### ISSUE THREAD

**Issue by mks-h** [Vanilla-OS/ABRoot#13]
Currently, ABRoot has 2 safeguards:
1. If a transaction failed obviously, discard changes
2. If the future system broke, users can boot back to the working system. Unless they did a new transaction on the future system.

I believe it's possible to skip the necessary reboot into the future system, while still having the same guarantees. I'd call this concept "past/present" in contrast to the current "present/future". The idea is to apply changes live, to the present partition, on a successful transaction. Then, after an eventual reboot, mark the partition as successfully booted. Successfully booted partition is an eventual replacement for the "past" partition. After a user makes another successful transaction, the successfully booted present partition becomes the "past" one, and changes are applied on the new present partition.

This makes it easier to modify the host system, but still keeps the old bootable system around.

**Comment by delight-aug** [comment]
This would also fix the problem of losing internal changes to the system that happened after an update but before reboot. But instead, it would bring back the usual problems of live updates.

Well, I guess this would require offline updates. But if we talk about a system with a bunch of user-installed native packages, offline updates are a necessity anyway.

**Comment by taukakao** [comment]
This just solves the minor inconvenience of rebooting, while introducing the major risks of live updates.

**Comment by mks-h** [comment]
I'd say it *brings back* the *currently minor* risks of live rebooting, with a *major* conveniences of conventional distributions, while keeping other safety guarantees. And 11 month ago the idea seemed to be having something very close to regular Ubuntu, but with vanilla GNOME, some more safety and possibility of installing anything. 

Right now though, I don't think it makes sense to keep this issue open.
