### ISSUE TITLE
Possible features for AB-R / APX

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [Vanilla-OS/ABRoot#14]
2 repos will be included.

One is ONLY for AB-Root & One is ONLY for APX.

AB-Root = https://github.com/ashos/ashos

APX = https://github.com/skiffos/SkiffOS

Would these be beneficial in anyway, shape or form?

**Comment by pietrodicaprio** [comment]
Please explain better, what should we do with those repositories?

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Please explain better, what should we do with those repositories?

SkiffOS for VanillaOS...

SkiffOS is a config package system for the Buildroot OS cross-compiler.

Run any distribution anywhere: decouples hardware support from user distro environments.
Reliable: minimal read-only host system for unbreakable boot-ups and over-the-air updates.
Reproducible: offline builds, pinned package versions, source-controlled custom configs.

Linux devices have varying requirements for kernel, firmware, and other hardware support packages. SkiffOS decouples this support from the containerized environments. The containers are portable across devices with the same CPU architecture, while ordinary OS images (Board Support Packages) are not.

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Please explain better, what should we do with those repositories?

AshOS for VanillaOS.

You always wanted to try Fedora Rawhide but after a few days, its fragility got on your nerves. Then, maybe you tried Fedora Silverblue Rawhide but then its complicated and slow git-like ostree operations killed your mood! Well, no more! Now you can try this bleeding edge distro (and many more distros like Debian sid) with more peace of mind.

AshOS is a unique meta-distribution that:

aims to bring immutability even to distros that do not have this very useful feature i.e. Arch Linux, Gentoo, etc.
wraps around any Linux distribution that can be bootstrapped (pretty much any major distribution)
targets to become a universal installer for different distros and different Desktop Environments/Window Managers
can install, deploy and multi-boot any number of distros
Initially inspired by Arch Linux, AshOS uses an immutable (read-only) root filesystem to set itself apart from any other distro out there. Software is installed and configured into individual snapshot trees, which can then be deployed and booted into. It does not invent yet another package format or package manager, but instead relies on the native package manager for instance pacman from Arch.

Ashes are one of the oldest trees in the world and they inspired naming AshOS.

In AshOS, there are several keywords:

Vanilla: we try to be as close to the "vanilla" version of target distribution that is being installed.
Minimalism: we adhere to a lego build system. Start small and build as complex a system as you would like. The main focus of development is on having a solid minimal installed snapshot, based on which user can have infinite immutable permutations!
Generality: We strive to cater for the most common denominator between distros and architectures (x64, aarch64, sparc, etc). As such, when there is a choice between convenience and comprehensiveness/generality, we go with the latter. To clarify with an example, it might be easier to use grub-btrfs instead of implementing our own GRUB update mechanism, but because that particular package might not be readily available in all distros, we develop an AshOS specific solution. This way, we can potentially cater to any distro in future!

**Comment by OpenOS-Project-Creator-Founder** [comment]
> Please explain better, what should we do with those repositories?

In essence adding both to VanillaOS could allow expand its reproducibility & modularity. 

Along with the powers of SkiffOS allow building/compiling VanillaOS itself for different BSPs.

**Comment by mirkobrombin** [comment]
Vanilla OS already has its own stack for immutability, atomicity and a solution, created in collaboration with Luca of Distrobox, for application containerization. Thanks for your feedback.
