### ISSUE TITLE
[kinetic] Unable to use abroot after reboot

### ISSUE THREAD

**Issue by johnbie** [Vanilla-OS/ABRoot#143]
I'm getting the following error:
```
Transactions are locked, another one is already running or a reboot is required.
```

I rebooted several times and rolled back transactions, but still can't use `abroot` after making some installations. I used `abx` during the transaction as well.

I get the following diff:
```
$ sudo abroot diff
SUCCESS  Gathering changes made by transaction...                                                                                                                                   
Removed:


Added:


Modified:
 • /etc/fstab
 • /etc/cups/subscriptions.conf
 • /etc/cups/subscriptions.conf.O
 • /usr/sbin/grub-mkconfig
```

**Comment by masza1** [comment]
Same with me, after several reboot abroot shell still can't access


how to solve it ?

**Comment by mirkobrombin** [comment]
Closing since Kinetic is deprecated
