### ISSUE TITLE
Can't control the apt command using ABRoot

### ISSUE THREAD

**Issue by HaroleDev** [Vanilla-OS/ABRoot#148]
![Screenshot from 2023-11-01 16-28-35](https://github.com/Vanilla-OS/ABRoot/assets/47141290/8b408eb8-8a61-4728-aa80-904a0894ebf8)

On ABRoot 2.0.0-alpha.1 (in Vanilla OS 2.0 alpha 10/16/2023), I can't control the CLI when I accidentally selected some packages that requires additional condition, which I can't access. As a result, I can't get past through the error.

**Comment by mirkobrombin** [comment]
The ABRoot transaction cannot be interactive. If a package asks for your intervention, that's probably something you should not install using ABRoot.

I'll take a look if that's something we can work around.
