### ISSUE TITLE
os-prober disabled by ABRoot

### ISSUE THREAD

**Issue by VladShmi** [Vanilla-OS/ABRoot#171]
VanillaOS Orchid. I am encountering an issue where the os-prober is "forever" disabled, even if I enable it in /etc/default/grub. I suspect that it's because of ABRoot recipe that keeps it disabled after a transaction like in the picture below. That prevents me from booting other operating systems like Windows. A good idea would be a switch or something to enable or disable it in the  ABRoot recipe.

![rn_image_picker_lib_temp_be987be8-9588-4675-95cc-c9be09a2d348](https://github.com/Vanilla-OS/ABRoot/assets/28844617/f373a979-c2cb-4115-a731-7d07e4d90d5e)

**Comment by taukakao** [comment]
As I thought, the grub-mkconfig command runs in chroot so it doesn't see the overlay mount of etc.
Thus, the default grub config from /part-future is always used.

**Comment by taukakao** [comment]
Will be closed by #229 and https://github.com/Vanilla-OS/core-image/pull/34
