### ISSUE TITLE
running abroot on the previous volume

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#180]
If you run abroot on the previous volume instead of the current one it will install to the current partition but still select the previous partition as the current one. 

To the user this would look like nothing changed apart from the default entry in grub. 

Maybe it would make sense to require a rollback before.

**Comment by matbme** [comment]
I implemented a check to prevent this but apparently it stopped working somewhere down the line. I'm testing a different approach.

**Comment by taukakao** [comment]
@matbme mirko preferred an approach where abroot would just not do the grub swap but still perform the operation.

**Comment by matbme** [comment]
> @matbme mirko preferred an approach where abroot would just not do the grub swap but still perform the operation.

[This line](https://github.com/Vanilla-OS/ABRoot/blob/aac90937fe4e78c8a1883389f650e6675dce8697/core/system.go#L911) was supposed to do exactly that, but I think my implementation is wrong. I'm testing a different check.
