### ISSUE TITLE
ABRoot doesn't check if package exists before removing it

### ISSUE THREAD

**Issue by VladShmi** [Vanilla-OS/ABRoot#193]
VanillaOS Orchid Alpha build 100. ABRoot doesn't clear selection after reboot if not applied. For example I selected epiphany-browser (if it I select epiphany, it "removes" it successfully, but after reboot is still there) and gnome-totem (which doesn't exist) and ABRoot doesn't let me apply changes because of gnome-totem. I can't even upgrade or force an upgrade, because is still fails. But after reboot selection is still there, i only select epiphany-browser so now when i apply I have "... pkg add epiphany-browser gnome-totem epiphany-browser" so you can never change the status of system because is buged like that.

Clarification by Tau: 
~~While abroot checks if a package exists when using pkg add, it doesn't do that on pkg remove. This causes abroot to fail when removing an nonexistent package.~~

Currently, when running abroot pkg apply or abroot upgrade, ABRoot will try to uninstall all packages the user specifies, even if they don't exist in the repos, which makes abroot fail.

Since ABRoot should be able to uninstall custom packages which are not in the repos it should probably just check if the packages are installed before uninstalling them.

This is a concern because if a package gets renamed or removed from the debian repos, automatic upgrades will fail and it needs user intervention, which is not ideal.

**Comment by taukakao** [comment]
You shouldn't install software with ABRoot, just drivers. 

And I don't quite get what you are saying, what exactly is failing when you do abroot upgrade -f ?

**Comment by VladShmi** [comment]
when I do abroot upgrade, abroot upgrade -f or abroot pkg apply, everything fails, because like i said before "gnome-totem" doesn't exist

**Comment by taukakao** [comment]
Those apps are installed via flatpak. Either use Gnome Software or the "flatpak --user " command to remove them.

**Comment by taukakao** [comment]
Though this is indeed a bug. ABRoot should check if the package exists when removing. 

To fix your abroot config, type in 
`host-spawn pkexec nano /etc/abroot/packages.remove`
Remove the stuff you don't need and save the file

**Comment by mirkobrombin** [comment]
Fixed by https://github.com/Vanilla-OS/ABRoot/commit/e5aa9f049ba90d1aa53e98389059c105c0b0e5ad
