### ISSUE TITLE
Use overlayfs for /opt

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#221]
Apparently, some ppas like chrome or 1password install their files to /opt 
So a custom image using those ppas won't work since these files are shadowed by the mount of /var/opt in /opt

We could instead use an overlayfs for /opt with lower /.system/opt and upper /var/opt

This is a significant change so maybe something for after beta.

A workaround is to create symlinks in /opt /* to /.system/opt/*

**Comment by mirkobrombin** [comment]
We could follow the same structure as per /etc
