### ISSUE TITLE
[orchid] Doesn't remember password after update

### ISSUE THREAD

**Issue by Bohne13** [Vanilla-OS/ABRoot#250]
After running
```shell
abroot upgrade
```
and restart the system, it does not remember the authentication password.

So after restarting the system and run the upper command again in the 'dgx' terminal,
there is a prompt for 'authentication required'.
When I try entering my password it tells me 'Sorry, it didn't work. Please try again!'

When I restart on the previous partition, it works totally fine!

FYI: Tried entering password multiple times, I really did it right!

Not sure if it is a problem of ABRoot or with a separate component, which handles the authentication process.

**Comment by Bohne13** [comment]
I have further noticed, it's a general problem with user-account authentication.

So I can login to my user the first time after start.
If I want to login again after display was locked, it doesn't remember my password.

Maybe it's a problem with some gnome components.
I don't know what system components is responsible for handling authentication and login?!?

**Comment by taukakao** [comment]
Could you try changing the password in the settings.

**Comment by Bohne13** [comment]
Have tried, doesn't work.
The problem isn't the password (because it worked on several updates before on vanillaOS 2.0).
I can't change my password because the system (maybe some gnome component responsible for 'super user' / authentication) doesn't remember my password.

I have hoped more people run into this problem after `abroot upgrade` there systems.

**Comment by taukakao** [comment]
No, it's not reproducible, it must be something with your specific install. (Not that that's ok then) 

Is the password promt asking for your account password or the root password?

**Comment by Bohne13** [comment]
Because VanillaOS is an A/B install it's easy to go to the previous partition where everything works fine.
So maybe with new updated the problem is gone.
Is there a was (online on a website or so) when there are new updates and which components are updated?

So at the user login screen it doesn't accept my account password. for executing `abroot upgrade` I'm not sure, but would think it asks for the root password. 
Anyway on my system both should be the same.

BTW thanks for support!

**Comment by taukakao** [comment]
Since it's a beta updates are too frequent to really do something like this. 

But you can always try upgrading once in a while from the working partition.

**Comment by fluoriteByte** [comment]
try using the continuous build from abroot's release page to see if the latest EtcBuilder fixes it

**Comment by Bohne13** [comment]
So after using the latest version of abroot and updating the whole system, everything seems to work fine.
