### ISSUE TITLE
PR workflow doesn't check out PR

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#252]
Instead, it just checks out the main branch, I think.

**Comment by kbdharun** [comment]
> Instead, it just checks out the main branch, I think.

I went through the workflow again, I am sure it checks out the respective PRs branch for the changes. What issue are you facing with it?

**Comment by taukakao** [comment]
@kbdharun 
I added a debugging step in a fork here called"Cat file":
https://github.com/taukakao/ABRoot/blob/main/.github/workflows/go-pr.yml

Then I made a PR where I added a file called testfile.

The resulting workflow run didn't have this file:
https://github.com/taukakao/ABRoot/actions/runs/8681208020/job/23803499807?pr=3

**Comment by kbdharun** [comment]
Interesting, I will check it out and get back.

**Comment by kbdharun** [comment]
Seems like this issue is when we specify Pull request targets, I checked it with the generic `on: pull_request` tag and now it works properly https://github.com/Vanilla-OS/ABRoot/actions/runs/8700689675/job/23861319067.
