### ISSUE TITLE
ABRoot doesn't correctly delete old image

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#255]
This requires more testing, but ABRoot leaves behind an old image on every upgrade. This makes the storage folder (/var/lib/abroot/storage) run full very quickly. 

I mean the issue has been around for a long time, it just didn't seem important enough to make an issue before.

**Comment by kbdharun** [comment]
Can confirm I have the same issue on a very old installation where storage gets full during `abroot upgrade`.

**Comment by taukakao** [comment]
@kbdharun 
To fix an old installation affected by this, it's enough to just delete /var/lib/abroot/storage/*
ABRoot will then just download the newest image completely.

**Comment by taukakao** [comment]
Ok, found a working solution. Just deleting the image with the correct digest works. Since ABRoot always creates a new image ontop of the downloaded one, this works. (It will not delete the layers, just the reference to the image.

**Comment by taukakao** [comment]
I will make a PR after some testing and polishing

**Comment by JonnyB247** [comment]
I can't get to /var/lib/abroot. Is it possible to escape the VSO shell?

**Comment by taukakao** [comment]
@JonnyB247 
Yes, with `host-shell`. Also note that you have to use pkexec since sudo is not available on the host.
