### ISSUE TITLE
File permission copy seems to squash read owner, group other's read

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/ABRoot#270]
Idk if this bug is caused by EtcBuilder or ABroot but it seems like after an upgrade, files in /etc where only the owner can read them get changed so that owner, group and others can read them which causes a breakage in NetworkManager

**Comment by axtloss** [comment]
Could you open this issue in the Etcbuilder repo, this isn't an issue with abroot

**Comment by fluoriteByte** [comment]
Issue transfer to https://github.com/linux-immutability-tools/EtcBuilder/issues/13

**Comment by fluoriteByte** [comment]
Also maybe cancel that project automation's thingy, this isnt 100℅ solved

**Comment by taukakao** [comment]
Fixed in #274
