### ISSUE TITLE
Abroot upgrade on Orchid + luks completed successfully, but then fails to mount /var - new `/dev/` is empty

### ISSUE THREAD

**Issue by michal-kurz** [Vanilla-OS/ABRoot#277]
I had a clean install of Orchid ([release 122](https://github.com/Vanilla-OS/live-iso/actions/runs/8482851316) I think), with no prior upgrades. 

After running `abroot upgrade`, my system fails to mount /var partition: 
![2195af38-3a3e-4b2d-8a8d-b4f64347ba7c](https://github.com/Vanilla-OS/ABRoot/assets/60649408/55242c39-1ae0-470a-a3b9-dfe93457dff7)

I also tried running the upgrade on newest abroot with the same results and saved the output this time: https://pastebin.com/e2dLe64B

I rolled back and compared root-a and root-b - both partitions were referencing luks mappers in `/dev/mappers`, but in root-a the `/dev` directory was completely empty - this seems to be the cause of failed mount to me, but  I have no idea how that state was reached.

**Comment by taukakao** [comment]
This is most likely fixed or at least different now due to https://github.com/Vanilla-OS/ABRoot/commit/24c1c14e62a5a5854b25841a86980c9cd238714c, so I'm closing this.
Feel free to reopen or open a new one if the issue still persists.
