### ISSUE TITLE
Lockfile doesn't get removed after an operation

### ISSUE THREAD

**Issue by matbme** [Vanilla-OS/ABRoot#283]
When running an upgrade or apply operation, the lockfile remains in `/tmp` even after a reboot, which prevents running any other operation until it is manually deleted.

**Comment by taukakao** [comment]
I can't reproduce this. 
After an upgrade, the lock file is successfully removed. 
The issue I see is that it is created when trying to auto-upgrade on boot.

**Comment by matbme** [comment]
Weird. I can reproduce this in both a fresh install and an older one after updating. I'll look deeper into this when I have the time.

**Comment by taukakao** [comment]
@matbme Are you checking right after the upgrade or after the reboot?

**Comment by matbme** [comment]
> @matbme Are you checking right after the upgrade or after the reboot?

Both. It's there before and after the reboot.

**Comment by taukakao** [comment]
Yeah, so after rebooting it is actually cleared but then abroot is executed by vso so the lockfile is there again.

**Comment by mirkobrombin** [comment]
![image](https://github.com/Vanilla-OS/ABRoot/assets/9479903/d057e7ff-44de-4edb-b2a0-2458c9b86080)
the lock disappear both when it fails or succeed so I think that transaction was still running so the lock file was being preserved, the only reason the lock file don't get deleted is in case abroot crashes or get killed, which I think is not the case

**Comment by taukakao** [comment]
@mirkobrombin 
Abroot is not running when the lock file exists after upgrading. 

Note that abroot is running multiple times (3-4 times) by vso which might have something to do with this.

**Comment by mirkobrombin** [comment]
Maybe the sysd timer is not working as expected and then keep running it
