### ISSUE TITLE
applications take very long to start

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/ABRoot#302]
### Issue Description

After logging out and back in, applications launched through GNOME take a very long time to start.

### Steps to Reproduce

- (re-)boot system
- log out
- log in
- start app

### On what version of Vanilla OS this happens?

Unreleased

**Comment by Guztaver** [comment]
> host-shell file /etc/mtab

Yeah, now I see that the link is broken.
![image](https://github.com/Vanilla-OS/ABRoot/assets/39814943/e0b97ab6-6d6c-4786-a445-61d36963366e)
