### ISSUE TITLE
Feature request: support other Docker Registries like quay or docker hub

### ISSUE THREAD

**Issue by fluoriteByte** [Vanilla-OS/ABRoot#339]
Github Container Registry is pretty unbearably slow, docker.io and quay.io are genuinely way faster, so i tried to make a mirror for vanilla, successfully (after 3 attempts) its at https://quay.io/repository/fluoritebyte/vanillaos-mirror-unofficial

the problem is that there is no sensible abroot config that i tried that worked for quay.io

the url that abroot forms to get the token seems to exclusively work with github, as it fails for docker hub.
and for the case of quay, it seems to accept 404 page as a valid response and continues with hasUpdate which then fails because quay (presumably) responds with an html/xml-like message, i do not know where to go from here

if anyone here that is knowledgeable about the insides of abroot and wants to help me, please do, im tired of waiting for updates to install at 100 kbit/s

**Comment by taukakao** [comment]
(I changed the title, if this feature is implemented then someone can still comment here and close it)

**Comment by rpickler** [comment]
I was really disappointed to find this limitation, as I run my own gitlab instance and would prefer my custom images to be hosted there.  So, I did a little digging.

The issue we have both run into appears to stem from [this line](https://github.com/Vanilla-OS/ABRoot/blob/main/core/registry.go#L76).  On gitlab, the token comes from `https://gitlab.private.domain/jwt/auth?scope=repository:...:pull&service=container_registry` whereas the image comes from `https://registry.private.domain`.  In GitHub, they appear to make these endpoints available all on `ghcr.io`.  For gitlab, they're on separate urls, and it appears the same is true of docker.io as well.

I'm curious how the myriad of OCI tools handle this as pulling a container is universally transparent between them.

**Comment by axtloss** [comment]
Each registry returns the authentication URL in the response headers, which is what abroot should be using to get the proper url
I've implemented this before in a custom client here https://github.com/axtloss/JshipIT/blob/main/src/main/java/io/github/jshipit/DockerAPIHelper.java#L46
I'll make a pr later to fix this
