### ISSUE TITLE
[kinetic] Unable to update with or use ABRoot: Failed to start transactional shell: exit status 11.

### ISSUE THREAD

**Issue by blake-lucas** [Vanilla-OS/ABRoot#34]
I'm unable to update my system or perform any transactions that require ABRoot. When using either abroot exec or abroot shell, I receive:
Failed to start transactional shell: exit status 11

Attempting to update via VSO ends up throwing the same error.

Even trying an empty transaction like this results in a failure:
sudo abroot shell
exit 0

Full ABRoot transaction output:
https://hastebin.com/moceloxeno.yaml

I originally ran into this with abroot 1.3.0 and vso 1.3.0. I was able to start applying transactions again after several reboots for seemingly no reason and am now on abroot 1.3.3 and vso 1.3.1-3. Now running into the same issue again after applying updates.

**Comment by blake-lucas** [comment]
After some troubleshooting, I was able to get ABRoot working again after manually booting into my previous root (spam CTRL+S while booting until at GRUB selection) then rebooting again. Seems like a bug but I'm not sure if there is any additional log info to dig deeper.

**Comment by mirkobrombin** [comment]
Thanks for reporting!

**Comment by bleonard252** [comment]
I'm now having this too. I rolled back with `abroot rollback` and it hasn't fixed this. Manually updating through abroot rather than vso appears to perform the full sync then returns 11, and no changes seem to be made.

**Comment by prateekmedia** [comment]
Same Issue, I tried to update grub file and did `sudo abroot exec echo` but it exited with code 11.

**Comment by pedro-hro** [comment]
Had the same issue here and the rollback didn't solved it.

**Comment by tetrahedronix** [comment]
Had the same issue with VirtualBox guest additions. On exit the system prints the error message.
I followed the instruction of this [blog article](https://handbook.vanillaos.org/2023/01/21/install-in-vm.html#title12)

**Comment by mirkobrombin** [comment]
I am investigating this but I am unable to replicate. Can someone provide some more logs since the link in the first comment is broken?

**Comment by erifre** [comment]
Had this problem today. Don't know how it happened but think a failed transaction made the future partition have too little space to create a new transaction.

Managed to solve it by doing `rm -rf /partFuture/.system /partFuture/.system_new` and then `cp -r /.system /partFuture/.system` . After that I was able to create a transaction with `abroot shell`.

Have tried both A and B and both seem to work.

**Comment by erifre** [comment]
> @tobehn The solution of erifre was for Orchid. In kinetic (stable), it will probably break the system.

I'm running kinetic and I had to use my solution once more to get my system back to running after getting an exit status 11.

**Comment by taukakao** [comment]
Oh, sorry for the misinformation then.

**Comment by tobehn** [comment]
I am also running kinetic.
It is because there is no space left on the device.

It will be a problem with the root partition. Is there any place where i can find information on how to increase the root partitions?
Is there a way to directly migrate to Orchid?
