### ISSUE TITLE
missing obvious way to add 3rd part apt source 

### ISSUE THREAD

**Issue by KUKARAF** [Vanilla-OS/ABRoot#354]
For any surface device to work right now surface kernel needs to be added to the sources and applied to system. 
It seems older versions of ABroot had a shell option but with version 2.0.1 it seems the command shell is not available and therefore no obvious way of adding custom apt sources like for surface kernel.

**Comment by mirkobrombin** [comment]
Because you can't. The proper way is using a custom Vib image. https://github.com/Vanilla-OS/custom-image

Here the documentation https://docs.vanillaos.org/collections/vib

We'll cover this in our handbook as well soon.

**Comment by KUKARAF** [comment]
Thank you for taking the time to explain

**Comment by KUKARAF** [comment]
Thank you for taking the time to explain

**Comment by KUKARAF** [comment]
After doing research i do not believe a VIB is the appropriate tool for the job. If i understood this correctly VIB is meant to create images that are launched within vanilla os as a docker/podman image. 

What i want to archive is use the surface-linux custom kernel on the base image and not in a subsystem. Unless i am missing something, i do not see a way to make my surface book 2, with its weird microsoft hardware, work without the custom kernel.

**Comment by KUKARAF** [comment]
Nevermind. I misunderstood. Please ignore the comment above.
