### ISSUE TITLE
after abroot pkg apply now VanillaOS thinks I have encrypted /var partition

### ISSUE THREAD

**Issue by anika200** [Vanilla-OS/ABRoot#371]
This is kinda maddening. I have just did fresh install, did a couple boots all was fine. Added a couple flatpaks and then decided I needed git so I installed via abroot pkg add git and then abroot pkg apply and then rebooted. Now I can't even get into my laptop because for some reason when the initramfs got rebuilt it thinks I have an encrypted partition and fails out. 
![PXL_20241008_204005260 MP](https://github.com/user-attachments/assets/ccb77481-7d91-4565-96b4-e8ada7fcd07d)
and also

![PXL_20241008_204201273](https://github.com/user-attachments/assets/11d525bf-4e25-41f0-85bc-bda5c0496c03)

Is there anything that can be done?

**Comment by anika200** [comment]
Can anyone tell me if this hook was run because I added a cache to the VG vos-var and possibly triggered something or we think it is just random bug? I am about to create the same cache for the VG/ssd again so if anyone out there knows anything please speak to me, I don't want to have to start over again.

**Comment by mirkobrombin** [comment]
I am looking at our check and I do not see why this happen. Can you try removing that cache for testing purposes?

https://github.com/Vanilla-OS/core-image/blob/5c275fea36abde95b44c2866f09033f868c2d9d1/includes.container/usr/share/init.d/090-abroot-unlock-var.sh#L39

**Comment by anika200** [comment]
Nothing could be done with that cache, had to start over. 
I am looking at that hook lines 39-45 and do wonder if it somehow caught something I did. I am going to try again only now I know to check the partition label vs disk label once I run the same commands I did before. For some reason it thought I switched to encrypted which I did not but maybe somehow the part/disk label changed???
Probably operator error of course.

**Comment by mirkobrombin** [comment]
It's possible, yes

**Comment by anika200** [comment]
OK, definitely not a bug. User error, for some reason I assumed all the kernel modules needed would be built into initramfs but that is not the case. 
The kernel modules needed are dm_cache and dm_writecache and possibly dm_cache-smq.
Currently I am trying to understand how to get them built into the initramfs so they are available during boot.
Not sure if this would be something to consider to put into the standard distro by default or not?

**Comment by mirkobrombin** [comment]
you can simply edit [this](https://github.com/Vanilla-OS/core-image/blob/dev/includes.container/etc/initramfs-tools/modules) file locally and then execute `abroot update-initramfs` to update it.

**Comment by anika200** [comment]
Thank you so much, have a great day.
