### ISSUE TITLE
Changing partitions for subvolumenes

### ISSUE THREAD

**Issue by lavilao** [Vanilla-OS/ABRoot#39]
Hi, I just watched the brodie robertson video about ABRoot and was thinking "wouldn't be possible to replace the roota and rootb partitions for roota and rootb subvolumenes?" this would have 
the advantage of:
1- just needing 1 root partition (as roota and rootb are subvolumenes)
2- reducing the amount of space required by 1/2 (if reflinks are used to sync roota and rootb then only the delta is added)
3- instant sync between the two roots (again if reflinks are used to sync then it should be instant)
the drawbacks:
1- the installer would have to be modified to make use of the new subvol layout
2- ABRoot should be modified to use the subvolumenes instead of partitions
3- insert here problem I have not realized yet
So, is it feasible? it was already in development? or it has way too many problems that I don't see?

**Comment by mirkobrombin** [comment]
ABRoot is meant to support any fs. The intention is to adopt this approach soon in Vanilla OS.

**Comment by lavilao** [comment]
Yay!
