### ISSUE TITLE
ABRoot + KDE Neon Editions

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [Vanilla-OS/ABRoot#40]
Could ABRoot have several root partitions, in regards to KDE Neon? To have a root partition for each Neon Edition & have them all use the same boot partition & home partition?

KDE Neon = https://neon.kde.org/download

User Edition 64-bit

Featuring the latest officially released KDE software on a stable base. Ideal for everyday users.

Developer Edition 64-bit

Unstable Editon plus development libraries pre-installed.

Testing Edition 64-bit

Featuring pre-release KDE software built the same day from bugfix branches. Good for testing. There is no QA. Will contain bugs.

Unstable Edition 64-bit

Featuring pre-release KDE software built the same day from new feature branches. Good for testing. There is no QA. Will contain many bugs.

**Comment by mirkobrombin** [comment]
Hi. We develop the technology and use it in Vanilla OS. Feel free to use in any other distro :)
