### ISSUE TITLE
Apx, ABRoot: Wrong translation license

### ISSUE THREAD

**Issue by comradekingu** [Vanilla-OS/ABRoot#46]
https://github.com/Vanilla-OS/ABRoot/blob/042f7441e3e98ab360a4a4c4bcb4bd37d84ad451/man/abroot.1#L58 
and
https://github.com/Vanilla-OS/ABRoot/blob/9864b9dc0259421c7778a38f7518646d40914346/man/sv/abroot.1#L58
say GPLv3-or-later, whereas
https://hosted.weblate.org/projects/vanilla-os/abroot/#information is limited to GPLv3-only.

**Comment by kbdharun** [comment]
Thanks for reporting it, I will switch soon.

**Comment by kbdharun** [comment]
I will switch the translation license for both Apx and ABRoot to GPL v3 or later now as the man page seems to be under it. 

Will make a formal announcement soon.

**Comment by kbdharun** [comment]
Done, thanks.
