### ISSUE TITLE
Resize the disk?

### ISSUE THREAD

**Issue by FNsi** [Vanilla-OS/ABRoot#58]
20gb is not enough for me, how can I solve it without breaking anything?

**Comment by kbdharun** [comment]
> 20gb is not enough for me, how can I solve it without breaking anything?

You can use manual partitioning during installation to increase the size of the Root partitions. Also, we suggest using root only for essential applications like drivers and firmware, alternatively you can install the applications if available using `nix` subcommand in apx.

**Comment by FNsi** [comment]
Nah, used it for a month, now I need to install rocm for test. So seems no way to do anything except erase anything 😅
