### ISSUE TITLE
How do i edit /etc/default/grub?

### ISSUE THREAD

**Issue by enthusiastic2003** [Vanilla-OS/ABRoot#64]
I need grub to prob for Windows that was not present during the install. Whenever I edit /etc/default/grub, the change gets reverted in the next reboot. Also, update-grub doesn't do anything.

Please do help me with this. My Windows partition is not accessible presently.

**Comment by liam-clink** [comment]
I'm also having this issue on an old MacBook Pro, where I need to change the GRUB_CMDLINE_LINUX_DEFAULT to prevent constant freezing, and I also want to add the selection of boot options, so being unable to change the grub settings in this way is making VanillaOS unusable for me.

**Comment by taukakao** [comment]
I can't reproduce this problem. Could you please test if this is still an issue?
