### ISSUE TITLE
Broken `pkg apply` command

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/ABRoot#79]
I am currently testing ABRoot options in Orchid. So, on top of the default installation, I tried adding a couple of packages `git`, `meson`, `flatpak`, `go` using `sudo abroot pkg add` command. After adding I applied the changes using `sudo abroot pkg apply` it failed (Ref. [1]) as I misspelt the `golang` package name as `go`. Now, I tried removing it using `sudo abroot pkg remove go` and did a reboot. Post reboot I tried applying the update again and it failed. After which I tried removing the package again.

![image](https://github.com/Vanilla-OS/ABRoot/assets/26346867/54ec6470-4511-49e2-ba21-994de033e83a)

If you notice in the above image, the remove command is working separately and not checking for duplicate entries, when mishaps like this occur and `abroot rollback` isn't an option. I think we should allow editing the package list using maybe a`pkg edit` command.

**Comment by mirkobrombin** [comment]
replaced by https://github.com/Vanilla-OS/ABRoot/issues/88
