### ISSUE TITLE
convert cobra commands to use expected args

### ISSUE THREAD

**Issue by bketelsen** [Vanilla-OS/ABRoot#8]
https://linuxiac.com/vanilla-os-promising-idea-disappointing-implementation/

get rid of panic for index not found in empty arg slice

**Comment by mirkobrombin** [comment]
Related: https://github.com/Vanilla-OS/ABRoot/commit/7f0a965f801fba7243055b255da6b6b044e735ff, https://github.com/Vanilla-OS/ABRoot/commit/835687ed18fb4d9f21faaf2792af712172188422

**Comment by mirkobrombin** [comment]
Already addressed in ABRoot v2.
