### ISSUE TITLE
Hidden Folders not Persisted by ABRoot in Vanillaos

### ISSUE THREAD

**Issue by oldmanz** [Vanilla-OS/ABRoot#81]
Trying to use some software that needs to be installed in root.  (security stuff for work)
It needs to have at least one hidden folder in the `/opt/<software-name>/` folder.  (as in, the folder begins with `.`.

ABRoot does not see it as an added file when exiting the shell.

**Comment by taukakao** [comment]
opt is not immutable, it should be edited without abroot
